CREATE TABLE cc_batch_dtl
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	batch_seq     		varchar(100) NOT NULL,
	business_date 		datetime NOT NULL ,
	driver_seq    		varchar(100) NOT NULL,
	creation_time 		datetime NOT NULL ,
	creation_emp_seq      	varchar(100),
	edit_time     		datetime NULL ,
	edit_emp_seq  		varchar(100),
	done_settle_time      	datetime NULL ,
	done_settle_emp_seq   	varchar(100),
	processor_batch_ref   	char(20) NULL  
	,ImportDateTime datetime
)


CREATE TABLE dly_sys_cond_ttl_old
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	business_date 		datetime NOT NULL ,
	store_id      		varchar(100) NOT NULL ,
	mi_seq        		varchar(100) NOT NULL ,
	cond_mi_seq   		varchar(100) NOT NULL ,
	parent_price_lvl      	varchar(100) NOT NULL ,
	price_1_sls_cnt       	varchar(100) NOT NULL ,
	price_1_rtn_cnt       	varchar(100) NOT NULL ,
	price_1_dsc_ttl       	float NOT NULL ,
	price_1_sls_ttl       	float NOT NULL ,
	price_1_cost_ttl      	float NULL ,
	price_1_vat_ttl       	float NULL ,
	price_2_sls_cnt       	varchar(100) NOT NULL ,
	price_2_rtn_cnt       	varchar(100) NOT NULL ,
	price_2_dsc_ttl       	float NOT NULL ,
	price_2_sls_ttl       	float NOT NULL ,
	price_2_cost_ttl      	float NULL ,
	price_2_vat_ttl       	float NULL ,
	price_3_sls_cnt       	varchar(100) NOT NULL ,
	price_3_rtn_cnt       	varchar(100) NOT NULL ,
	price_3_dsc_ttl       	float NOT NULL ,
	price_3_sls_ttl       	float NOT NULL ,
	price_3_cost_ttl      	float NULL ,
	price_3_vat_ttl       	float NULL ,
	price_4_sls_cnt       	varchar(100) NOT NULL ,
	price_4_rtn_cnt       	varchar(100) NOT NULL ,
	price_4_dsc_ttl       	float NOT NULL ,
	price_4_sls_ttl       	float NOT NULL ,
	price_4_cost_ttl      	float NULL ,
	price_4_vat_ttl       	float NULL ,
	em_ttl_repl_seq       	varchar(100) NOT NULL
	,ImportDateTime datetime
)

CREATE TABLE dly_sys_maj_grp_ttl
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	business_date 		datetime NOT NULL ,
	store_id      		varchar(100) NOT NULL ,
	maj_grp_seq   		varchar(100) NOT NULL ,
	sls_cnt       		varchar(100) NOT NULL ,
	sls_ttl       		float NOT NULL ,
	rtn_cnt       		varchar(100) NOT NULL ,
	rtn_ttl       		float NOT NULL ,
	dsc_ttl       		float NOT NULL ,
	em_ttl_repl_seq       	varchar(100) NOT NULL 	
	,ImportDateTime datetime
)

CREATE TABLE dly_sys_mi_ttl
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	business_date 		datetime NOT NULL ,
	store_id      		varchar(100) NOT NULL ,
	mi_seq        		varchar(100) NOT NULL ,
	price_1_sls_cnt       	varchar(100) NOT NULL ,
	price_1_rtn_cnt       	varchar(100) NOT NULL ,
	price_1_dsc_ttl       	float NOT NULL ,
	price_1_sls_ttl       	float NOT NULL ,
	price_2_sls_cnt       	varchar(100) NOT NULL ,
	price_2_rtn_cnt       	varchar(100) NOT NULL ,
	price_2_dsc_ttl       	float NOT NULL ,
	price_2_sls_ttl       	float NOT NULL ,
	price_3_sls_cnt       	varchar(100) NOT NULL ,
	price_3_rtn_cnt       	varchar(100) NOT NULL ,
	price_3_dsc_ttl       	float NOT NULL ,
	price_3_sls_ttl       	float NOT NULL ,
	price_4_sls_cnt       	varchar(100) NOT NULL ,
	price_4_rtn_cnt       	varchar(100) NOT NULL ,
	price_4_dsc_ttl       	float NOT NULL ,
	price_4_sls_ttl       	float NOT NULL ,
	price_5_sls_cnt       	varchar(100),
	price_5_rtn_cnt       	varchar(100),
	price_5_dsc_ttl       	float NULL ,
	price_5_sls_ttl       	float NULL ,
	price_6_sls_cnt       	varchar(100),
	price_6_rtn_cnt       	varchar(100),
	price_6_dsc_ttl       	float NULL ,
	price_6_sls_ttl       	float NULL ,
	price_7_sls_cnt       	varchar(100),
	price_7_rtn_cnt       	varchar(100),
	price_7_dsc_ttl       	float NULL ,
	price_7_sls_ttl       	float NULL ,
	price_8_sls_cnt       	varchar(100),
	price_8_rtn_cnt       	varchar(100),
	price_8_dsc_ttl       	float NULL ,
	price_8_sls_ttl       	float NULL ,
	price_9_sls_cnt       	varchar(100),
	price_9_rtn_cnt       	varchar(100),
	price_9_dsc_ttl       	float NULL ,
	price_9_sls_ttl       	float NULL ,
	price_10_sls_cnt      	varchar(100),
	price_10_rtn_cnt      	varchar(100),
	price_10_dsc_ttl      	float NULL ,
	price_10_sls_ttl      	float NULL ,
	weight_ttl    		varchar(100) NULL ,
	em_ttl_repl_seq       	varchar(100) NOT NULL 	
	,ImportDateTime datetime
)

CREATE TABLE dly_rvc_fam_grp_ttl
(
	SerialKey			nvarchar(100) NOT NuLL PriMarY key,
	business_date 		datetime NOT NULL ,
	store_id      		varchar(100), 
	rvc_seq       		varchar(100), 
	fam_grp_seq   		varchar(100), 
	sls_cnt       		varchar(100), 
	sls_ttl       		varchar(100), 
	rtn_cnt       		varchar(100), 
	rtn_ttl       		varchar(100), 
	dsc_ttl       		varchar(100), 
	em_ttl_repl_seq     varchar(100)
)

CREATE TABLE dly_sys_tax_ttl
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	business_date 		datetime NOT NULL ,
	store_id      		varchar(100) NOT NULL ,
	tax_rate_seq  		varchar(100) NOT NULL ,
	coll_ttl      		float NOT NULL ,
	txbl_sls_ttl  		float NOT NULL ,
	exempt_ttl    		float NOT NULL ,
	em_ttl_repl_seq       	varchar(100) NOT NULL ,
	incl_tax_by_chk_itmzr_ttl     float NULL 	
	,ImportDateTime datetime
)

CREATE TABLE dly_sys_trk_ttl
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	business_date 		datetime NOT NULL ,
	store_id      		varchar(100) NOT NULL ,
	trk_grp_seq   		varchar(100) NOT NULL ,
	trk_cnt_01    		varchar(100) NOT NULL ,
	trk_ttl_01    		float NOT NULL ,
	trk_cnt_02    		varchar(100) NOT NULL ,
	trk_ttl_02    		float NOT NULL ,
	trk_cnt_03    		varchar(100) NOT NULL ,
	trk_ttl_03    		float NOT NULL ,
	trk_cnt_04    		varchar(100) NOT NULL ,
	trk_ttl_04    		float NOT NULL ,
	trk_cnt_05    		varchar(100) NOT NULL ,
	trk_ttl_05    		float NOT NULL ,
	trk_cnt_06    		varchar(100) NOT NULL ,
	trk_ttl_06    		float NOT NULL ,
	trk_cnt_07    		varchar(100) NOT NULL ,
	trk_ttl_07    		float NOT NULL ,
	trk_cnt_08    		varchar(100) NOT NULL ,
	trk_ttl_08    		float NOT NULL ,
	trk_cnt_09    		varchar(100) NOT NULL ,
	trk_ttl_09    		float NOT NULL ,
	trk_cnt_10    		varchar(100) NOT NULL ,
	trk_ttl_10    		float NOT NULL ,
	trk_cnt_11    		varchar(100) NOT NULL ,
	trk_ttl_11    		float NOT NULL ,
	trk_cnt_12    		varchar(100) NOT NULL ,
	trk_ttl_12    		float NOT NULL ,
	trk_cnt_13    		varchar(100) NOT NULL ,
	trk_ttl_13    		float NOT NULL ,
	trk_cnt_14    		varchar(100) NOT NULL ,
	trk_ttl_14    		float NOT NULL ,
	trk_cnt_15    		varchar(100) NOT NULL ,
	trk_ttl_15    		float NOT NULL ,
	trk_cnt_16    		varchar(100) NOT NULL ,
	trk_ttl_16    		float NOT NULL ,
	trk_cnt_17    		varchar(100) NOT NULL ,
	trk_ttl_17    		float NOT NULL ,
	trk_cnt_18    		varchar(100) NOT NULL ,
	trk_ttl_18    		float NOT NULL ,
	trk_cnt_19    		varchar(100) NOT NULL ,
	trk_ttl_19    		float NOT NULL ,
	trk_cnt_20    		varchar(100) NOT NULL ,
	trk_ttl_20    		float NOT NULL ,
	trk_cnt_21    		varchar(100) NOT NULL ,
	trk_ttl_21    		float NOT NULL ,
	trk_cnt_22    		varchar(100) NOT NULL ,
	trk_ttl_22    		float NOT NULL ,
	trk_cnt_23    		varchar(100) NOT NULL ,
	trk_ttl_23    		float NOT NULL ,
	trk_cnt_24    		varchar(100) NOT NULL ,
	trk_ttl_24    		float NOT NULL ,
	trk_cnt_25    		varchar(100) NOT NULL ,
	trk_ttl_25    		float NOT NULL ,
	trk_cnt_26    		varchar(100) NOT NULL ,
	trk_ttl_26    		float NOT NULL ,
	trk_cnt_27    		varchar(100) NOT NULL ,
	trk_ttl_27    		float NOT NULL ,
	trk_cnt_28    		varchar(100) NOT NULL ,
	trk_ttl_28    		float NOT NULL ,
	trk_cnt_29    		varchar(100) NOT NULL ,
	trk_ttl_29    		float NOT NULL ,
	trk_cnt_30    		varchar(100) NOT NULL ,
	trk_ttl_30    		float NOT NULL ,
	trk_cnt_31    		varchar(100) NOT NULL ,
	trk_ttl_31    		float NOT NULL ,
	trk_cnt_32    		varchar(100) NOT NULL ,
	trk_ttl_32    		float NOT NULL ,
	trk_cnt_33    		varchar(100) NOT NULL ,
	trk_ttl_33    		float NOT NULL ,
	trk_cnt_34    		varchar(100) NOT NULL ,
	trk_ttl_34    		float NOT NULL ,
	trk_cnt_35    		varchar(100) NOT NULL ,
	trk_ttl_35    		float NOT NULL ,
	trk_cnt_36    		varchar(100) NOT NULL ,
	trk_ttl_36    		float NOT NULL ,
	trk_cnt_37    		varchar(100) NOT NULL ,
	trk_ttl_37    		float NOT NULL ,
	trk_cnt_38    		varchar(100) NOT NULL ,
	trk_ttl_38    		float NOT NULL ,
	trk_cnt_39    		varchar(100) NOT NULL ,
	trk_ttl_39    		float NOT NULL ,
	trk_cnt_40    		varchar(100) NOT NULL ,
	trk_ttl_40    		float NOT NULL ,
	trk_cnt_41    		varchar(100) NOT NULL ,
	trk_ttl_41    		float NOT NULL ,
	trk_cnt_42    		varchar(100) NOT NULL ,
	trk_ttl_42    		float NOT NULL ,
	trk_cnt_43    		varchar(100) NOT NULL ,
	trk_ttl_43    		float NOT NULL ,
	trk_cnt_44    		varchar(100) NOT NULL ,
	trk_ttl_44    		float NOT NULL ,
	trk_cnt_45    		varchar(100) NOT NULL ,
	trk_ttl_45    		float NOT NULL ,
	trk_cnt_46    		varchar(100) NOT NULL ,
	trk_ttl_46    		float NOT NULL ,
	trk_cnt_47    		varchar(100) NOT NULL ,
	trk_ttl_47    		float NOT NULL ,
	trk_cnt_48    		varchar(100) NOT NULL ,
	trk_ttl_48    		float NOT NULL ,
	trk_cnt_49    		varchar(100) NOT NULL ,
	trk_ttl_49    		float NOT NULL ,
	trk_cnt_50    		varchar(100) NOT NULL ,
	trk_ttl_50    		float NOT NULL ,
	trk_cnt_51    		varchar(100) NOT NULL ,
	trk_ttl_51    		float NOT NULL ,
	trk_cnt_52    		varchar(100) NOT NULL ,
	trk_ttl_52    		float NOT NULL ,
	trk_cnt_53    		varchar(100) NOT NULL ,
	trk_ttl_53    		float NOT NULL ,
	trk_cnt_54    		varchar(100) NOT NULL ,
	trk_ttl_54    		float NOT NULL ,
	trk_cnt_55    		varchar(100) NOT NULL ,
	trk_ttl_55    		float NOT NULL ,
	trk_cnt_56    		varchar(100) NOT NULL ,
	trk_ttl_56    		float NOT NULL ,
	trk_cnt_57    		varchar(100) NOT NULL ,
	trk_ttl_57    		float NOT NULL ,
	trk_cnt_58    		varchar(100) NOT NULL ,
	trk_ttl_58    		float NOT NULL ,
	trk_cnt_59    		varchar(100) NOT NULL ,
	trk_ttl_59    		float NOT NULL ,
	trk_cnt_60    		varchar(100) NOT NULL ,
	trk_ttl_60    		float NOT NULL ,
	trk_cnt_61    		varchar(100) NOT NULL ,
	trk_ttl_61    		float NOT NULL ,
	trk_cnt_62    		varchar(100) NOT NULL ,
	trk_ttl_62    		float NOT NULL ,
	trk_cnt_63    		varchar(100) NOT NULL ,
	trk_ttl_63    		float NOT NULL ,
	trk_cnt_64    		varchar(100) NOT NULL ,
	trk_ttl_64    		float NOT NULL ,
	em_ttl_repl_seq       	varchar(100) NOT NULL 	
	,ImportDateTime datetime

)

CREATE TABLE dly_sys_ttl
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	business_date 		datetime NOT NULL ,
	store_id      		varchar(100) NOT NULL ,
	net_sls_ttl   		varchar(100) NOT NULL ,
	rtn_cnt       		varchar(100) NOT NULL ,
	rtn_ttl       		varchar(100) NOT NULL ,
	void_cnt      		varchar(100) NOT NULL ,
	void_ttl      		varchar(100) NOT NULL ,
	item_dsc_ttl  		varchar(100) NOT NULL ,
	sttl_dsc_ttl  		varchar(100) NOT NULL ,
	svc_ttl       		varchar(100) NOT NULL ,
	tax_coll_ttl  		varchar(100) NOT NULL ,
	credit_ttl    		varchar(100) NOT NULL ,
	rounding_ttl  		varchar(100) NOT NULL ,
	change_grand_ttl      	varchar(100) NOT NULL ,
	non_txbl_ttl  		varchar(100) NOT NULL ,
	cancel_cnt    		varchar(100) NOT NULL ,
	cancel_ttl    		varchar(100) NOT NULL ,
	mgr_void_cnt  		varchar(100) NOT NULL ,
	mgr_void_ttl  		varchar(100) NOT NULL ,
	error_correct_cnt     	varchar(100) NOT NULL ,
	error_correct_ttl     	varchar(100) NOT NULL ,
	chk_carry_over_cnt    	varchar(100) NOT NULL ,
	chk_carry_over_ttl    	varchar(100) NOT NULL ,
	chk_begun_cnt 		varchar(100) NOT NULL ,
	chk_begun_ttl 		varchar(100) NOT NULL ,
	chk_paid_cnt  		varchar(100) NOT NULL ,
	chk_paid_ttl  		varchar(100) NOT NULL ,
	gross_rcpts_ttl       	varchar(100) NOT NULL ,
	chgd_rcpts_ttl        	varchar(100) NOT NULL ,
	chgd_tips_ttl 		varchar(100) NOT NULL ,
	tip_svc_ttl   		varchar(100) NOT NULL ,
	tips_paid_ttl 		varchar(100) NOT NULL ,
	tips_decl_ttl 		varchar(100) NOT NULL ,
	labor_cat_1_reg_hrs   	varchar(100) NULL ,
	labor_cat_1_ovt_hrs   	varchar(100) NULL ,
	labor_cat_1_reg_ttl   	varchar(100) NULL ,
	labor_cat_1_ovt_ttl   	varchar(100) NULL ,
	labor_cat_2_reg_hrs   	varchar(100) NULL ,
	labor_cat_2_ovt_hrs   	varchar(100) NULL ,
	labor_cat_2_reg_ttl   	varchar(100) NULL ,
	labor_cat_2_ovt_ttl   	varchar(100) NULL ,
	labor_cat_3_reg_hrs   	varchar(100) NULL ,
	labor_cat_3_ovt_hrs   	varchar(100) NULL ,
	labor_cat_3_reg_ttl   	varchar(100) NULL ,
	labor_cat_3_ovt_ttl   	varchar(100) NULL ,
	labor_cat_4_reg_hrs   	varchar(100) NULL ,
	labor_cat_4_ovt_hrs   	varchar(100) NULL ,
	labor_cat_4_reg_ttl   	varchar(100) NULL ,
	labor_cat_4_ovt_ttl   	varchar(100) NULL ,
	non_rvc_labor_cat_1_reg_hrs   varchar(100) NULL ,
	non_rvc_labor_cat_1_ovt_hrs   varchar(100) NULL ,
	non_rvc_labor_cat_1_reg_ttl   varchar(100) NULL ,
	non_rvc_labor_cat_1_ovt_ttl   varchar(100) NULL ,
	non_rvc_labor_cat_2_reg_hrs   varchar(100) NULL ,
	non_rvc_labor_cat_2_ovt_hrs   varchar(100) NULL ,
	non_rvc_labor_cat_2_reg_ttl   varchar(100) NULL ,
	non_rvc_labor_cat_2_ovt_ttl   varchar(100) NULL ,
	non_rvc_labor_cat_3_reg_hrs   varchar(100) NULL ,
	non_rvc_labor_cat_3_ovt_hrs   varchar(100) NULL ,
	non_rvc_labor_cat_3_reg_ttl   varchar(100) NULL ,
	non_rvc_labor_cat_3_ovt_ttl   varchar(100) NULL ,
	non_rvc_labor_cat_4_reg_hrs   varchar(100) NULL ,
	non_rvc_labor_cat_4_ovt_hrs   varchar(100) NULL ,
	non_rvc_labor_cat_4_reg_ttl   varchar(100) NULL ,
	non_rvc_labor_cat_4_ovt_ttl   varchar(100) NULL ,
	grand_ttl     		varchar(100) NOT NULL ,
	grand_ttl_raw 		varchar(100) ,
	training_ttl  		varchar(100) NOT NULL ,
	business_date_start_time      varchar(100) ,
	business_date_end_time        varchar(100) ,
	business_date_start_time_gmt  varchar(100) ,
	business_date_end_time_gmt    varchar(100) ,
	em_ttl_repl_seq       	varchar(100) NOT NULL ,
	ind_tips_paid_ttl     	float NULL	
	,ImportDateTime datetime
)

CREATE TABLE fam_grp_def
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	fam_grp_seq   		varchar(100) NOT NULL ,
	obj_num       		varchar(100) NOT NULL ,
	name  			varchar(100) NULL ,
	cat   			varchar(100),
	last_updated_by       	varchar(100),
	last_updated_date     	datetime NULL ,
	multi_user_access_seq 	bigint NULL	
	,ImportDateTime datetime
)

CREATE TABLE maj_grp_def
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	maj_grp_seq   		varchar(100) NOT NULL ,
	obj_num       		varchar(100) NOT NULL ,
	cat   			varchar(100) NULL,
	name  			varchar(100) NULL,
	cos_grp_seq   		varchar(100) NOT NULL,
	acct_grp_seq  		varchar(100),
	last_updated_by       	varchar(100),
	last_updated_date     	datetime NULL ,
	multi_user_access_seq 	bigint NULL	
	,ImportDateTime datetime
)

CREATE TABLE mi_def
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	mi_seq        		varchar(100) NOT NULL ,
	obj_num       		varchar(100) NOT NULL ,
	name_1        		varchar(100) NULL ,
	name_2        		varchar(100) NULL ,
	maj_grp_seq   		varchar(100),
	fam_grp_seq   		varchar(100),
	mi_grp_seq    		varchar(100),
	mi_slu_seq    		varchar(100),
	price_grp_seq 		varchar(100),
	slu_priority  		varchar(100),
	nlu_grp       		varchar(100),
	nlu_num       		varchar(100),
	key_num       		varchar(100),
	icon_id       		varchar(100),
	ob_mi31_chk_mi_avail  	varchar(100),
	ob_mi44_no_edit_in_mgr_proc   varchar(100),
	ob_item_is_the_no_modifier    varchar(100),
	ob_lite_mi_dirty      	varchar(100),
	ob_rsvd01     		varchar(100),
	ob_rsvd02     		varchar(100),
	ob_rsvd03     		varchar(100),
	ob_rsvd04     		varchar(100),
	mi_type_seq   		varchar(100),
	cond_grp_mem_seq      	varchar(100),
	cond_req      		varchar(100),
	cond_allowed  		varchar(100),
	crs_mem_seq   		varchar(100),
	crs_sel_seq   		varchar(100),
	class_seq        	varchar(100),
	prn_def_class_seq     	varchar(100),
	product_seq_1 		varchar(100),
	product_seq_2 		varchar(100),
	product_seq_3 		varchar(100),
	product_seq_4 		varchar(100),
	comm_amt      		float NULL ,
	comm_pcnt     		float,
	cross_ref1    		varchar(100) NULL ,
	cross_ref2    		varchar(100) NULL ,
	last_updated_by       	varchar(100),
	last_updated_date     	datetime NULL ,
	ob_workstation_only   	varchar(100),
	mi_slu2_seq   		varchar(100),
	ob_flags      		integer NULL DEFAULT 0 ,
	multi_user_access_seq 	bigint NULL ,
	prep_time     		integer NULL ,
	external_type 		integer NULL	
	,ImportDateTime datetime
)

CREATE TABLE mi_dtl
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	trans_seq     		varchar(100) NOT NULL ,
	dtl_seq       		varchar(100) NOT NULL ,
	mi_seq        		varchar(100) NOT NULL ,
	ob_dtl04_rtn  		varchar(100),
	ob_dtl21_bev_aft_prompt       varchar(100),
	crs   			varchar(100),
	ob_tax_1_active       	varchar(100),
	ob_tax_2_active       	varchar(100),
	ob_tax_3_active       	varchar(100),
	ob_tax_4_active       	varchar(100),
	ob_tax_5_active       	varchar(100),
	ob_tax_6_active       	varchar(100),
	ob_tax_7_active       	varchar(100),
	ob_tax_8_active       	varchar(100),
	ob_modified_by_no     	varchar(100),
	sls_itmzr_seq 		varchar(100) NOT NULL ,
	price_lvl     		varchar(100) NOT NULL ,
	type_def      		binary(11) NOT NULL ,
	dsc_itmzr     		varchar(100),
	svc_itmzr     		varchar(100),
	print_grp     		varchar(100),
	surcharge_tax_ttl     	float NULL ,
	item_weight   		varchar(100) NULL ,
	combo_meal_num      varchar(100) NULL ,
	combo_side_num      varchar(100),
	vat_txbl_amt  		float NULL ,
	combo_grp_seq 		varchar(100),
	cndmnt_grp    		integer NULL ,
	price_lvl_original    	varchar(100) NULL ,
	print_class_seq       	varchar(100),
	refill_dtl_id 		integer NULL ,
	refill_base_price     	float NULL ,
	dining_course_seq     	varchar(100),
	combo_size    		integer NULL ,
	inclusive_tax_ttl_forgiven    float NULL	
	,ImportDateTime datetime
)

CREATE TABLE mi_grp_def
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	mi_grp_seq    		varchar(100) NOT NULL ,
	obj_num       		varchar(100) NOT NULL ,
	name  			varchar(100),
	cat   			varchar(100),
	last_updated_by       	varchar(100),
	last_updated_date     	datetime NULL ,
	multi_user_access_seq 	bigint NULL	
	,ImportDateTime datetime
)

CREATE TABLE mi_price_def
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	mi_seq        		varchar(100) NOT NULL ,
	mi_price_seq  		varchar(100) NOT NULL ,
	effective_from        	datetime NULL ,
	effective_to  		datetime NULL ,
	preset_amt_1  		float NULL ,
	preset_amt_2  		float NULL ,
	preset_amt_3  		float NULL ,
	preset_amt_4  		float NULL ,
	preset_amt_5  		float NULL ,
	preset_amt_6  		float NULL ,
	preset_amt_7  		float NULL ,
	preset_amt_8  		float NULL ,
	preset_amt_9  		float NULL ,
	preset_amt_10 		float NULL ,
	vat_txbl_1    		float NULL ,
	vat_txbl_2    		float NULL ,
	vat_txbl_3    		float NULL ,
	vat_txbl_4    		float NULL ,
	vat_txbl_5    		float NULL ,
	vat_txbl_6    		float NULL ,
	vat_txbl_7    		float NULL ,
	vat_txbl_8    		float NULL ,
	vat_txbl_9    		float NULL ,
	vat_txbl_10   		float NULL ,
	cost_1        		float NULL ,
	cost_2        		float NULL ,
	cost_3        		float NULL ,
	cost_4        		float NULL ,
	cost_5        		float NULL ,
	cost_6        		float NULL ,
	cost_7        		float NULL ,
	cost_8        		float NULL ,
	cost_9        		float NULL ,
	cost_10       		float NULL ,
	tare_weight   		varchar(100),
	surcharge_tax 		float NULL ,
	em_chg_set_seq      varchar(100) NULL,
	price_grp_seq 		varchar(100),
	price_tier_seq        	varchar(100),
	em_repl_status        	char(1) NULL ,
	comments      		varchar(80) NULL ,
	ob_rsvd01     		varchar(100),
	ob_rsvd02     		varchar(100),
	ob_rsvd03     		varchar(100),
	ob_rsvd04     		varchar(100),
	last_updated_by       	varchar(100)
	,ImportDateTime datetime
)

CREATE TABLE no_sale_dtl
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	trans_seq     		varchar(100) NOT NULL ,
	drwr_num      		varchar(100)	
	,ImportDateTime datetime
)

CREATE TABLE sale_dtl
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	trans_seq     		varchar(100) NOT NULL ,
	order_type_seq        	varchar(100) NOT NULL ,
	sls_itmzr_01  		float NOT NULL ,
	sls_itmzr_02  		float NOT NULL ,
	sls_itmzr_03  		float NOT NULL ,
	sls_itmzr_04  		float NOT NULL ,
	sls_itmzr_05  		float NOT NULL ,
	sls_itmzr_06  		float NOT NULL ,
	sls_itmzr_07  		float NOT NULL ,
	sls_itmzr_08  		float NOT NULL ,
	txbl_sls_itmzr_01     	float NOT NULL ,
	txbl_sls_itmzr_02     	float NOT NULL ,
	txbl_sls_itmzr_03     	float NOT NULL ,
	txbl_sls_itmzr_04     	float NOT NULL ,
	txbl_sls_itmzr_05     	float NOT NULL ,
	txbl_sls_itmzr_06     	float NOT NULL ,
	txbl_sls_itmzr_07     	float NOT NULL ,
	txbl_sls_itmzr_08     	float NOT NULL ,
	tax_exempt_sls_itmzr_01       float NOT NULL ,
	tax_exempt_sls_itmzr_02       float NOT NULL ,
	tax_exempt_sls_itmzr_03       float NOT NULL ,
	tax_exempt_sls_itmzr_04       float NOT NULL ,
	tax_exempt_sls_itmzr_05       float NOT NULL ,
	tax_exempt_sls_itmzr_06       float NOT NULL ,
	tax_exempt_sls_itmzr_07       float NOT NULL ,
	tax_exempt_sls_itmzr_08       float NOT NULL ,
	tax_itmzr_01  		float NOT NULL ,
	tax_itmzr_02  		float NOT NULL ,
	tax_itmzr_03  		float NOT NULL ,
	tax_itmzr_04  		float NOT NULL ,
	tax_itmzr_05  		float NOT NULL ,
	tax_itmzr_06  		float NOT NULL ,
	tax_itmzr_07  		float NOT NULL ,
	tax_itmzr_08  		float NOT NULL ,
	auto_svc_ttl  		float NOT NULL ,
	other_svc_ttl 		float NOT NULL ,
	net_sls_ttl   		float NOT NULL ,
	rtn_cnt       		varchar(100) NOT NULL,
	rtn_ttl       		float NOT NULL ,
	void_cnt      		varchar(100) NOT NULL,
	void_ttl      		float NOT NULL ,
	item_dsc_ttl  		float NOT NULL ,
	sttl_dsc_ttl  		float NOT NULL ,
	tax_coll_ttl  		float NOT NULL ,
	credit_ttl    		float NOT NULL ,
	non_txbl_ttl  		float NOT NULL ,
	rounding_ttl  		float NOT NULL ,
	change_grand_ttl      	float NOT NULL ,
	pymnt_ttl     		float NOT NULL ,
	training_ttl  		float NOT NULL ,
	cov_cnt       		varchar(100) NOT NULL,
	chk_begun_cnt 		varchar(100) NOT NULL,
	chk_paid_cnt  		varchar(100) NOT NULL,
	tbl_turn_cnt  		varchar(100) NOT NULL,
	tbl_dine_time 		varchar(100) NOT NULL ,
	ob_sl01_chk_prntd     	varchar(100),
	gross_rcpts   		float NOT NULL ,
	chg_rcpts_ttl 		float NOT NULL ,
	charged_tip_ttl       	float NOT NULL ,
	tip_svc_chg_ttl       	float NOT NULL ,
	mgr_void_cnt  		varchar(100) NOT NULL,
	mgr_void_ttl  		float NOT NULL ,
	error_correct_cnt     	varchar(100) NOT NULL,
	error_correct_ttl     	float NOT NULL ,
	ob_order_type_changed 	varchar(100),
	cur_ot_net_sls_ttl    	float NOT NULL ,
	cur_ot_cov_cnt        	varchar(100) NOT NULL,
	cur_ot_chk_cnt        	varchar(100) NOT NULL,
	cur_ot_tbl_turn_cnt   	varchar(100) NOT NULL,
	cur_ot_tbl_dine_time  	varchar(100) NOT NULL ,
	prev_ot_net_sls_ttl   	float NOT NULL ,
	prev_ot_cov_cnt       	varchar(100) NOT NULL,
	prev_ot_chk_cnt       	varchar(100) NOT NULL,
	prev_ot_tbl_turn_cnt  	varchar(100) NOT NULL,
	prev_ot_tbl_dine_time 	varchar(100) NOT NULL ,
	prev_order_type_seq   	varchar(100) NULL ,
	amt_due_ttl   		float NULL ,
	incl_tax_by_chk_itmzr_01      float NULL ,
	incl_tax_by_chk_itmzr_02      float NULL ,
	incl_tax_by_chk_itmzr_03      float NULL ,
	incl_tax_by_chk_itmzr_04      float NULL ,
	incl_tax_by_chk_itmzr_05      float NULL ,
	incl_tax_by_chk_itmzr_06      float NULL ,
	incl_tax_by_chk_itmzr_07      float NULL ,
	incl_tax_by_chk_itmzr_08      float NULL
	,ImportDateTime datetime
)

CREATE TABLE sales_itmzr_def
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	sls_itmzr_seq 		varchar(100) NOT NULL ,
	name  			varchar(100) NULL ,
	last_updated_by       	varchar(100),
	last_updated_date     	datetime NULL	
	,ImportDateTime datetime
)

CREATE TABLE tmed_def
(
SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	tmed_seq      		varchar(100) NOT NULL ,
	obj_num       		varchar(100) NOT NULL ,
	name  			varchar(100) NULL ,
	type  			varchar(100) NOT NULL ,
	ob_tmed01_open_drwr   	varchar(100),
	ob_tpay02_req_amt_entry       varchar(100),
	ob_tpay03_assume_pd_in_full   varchar(100),
	ob_tpay04_chk_endorse_req     varchar(100),
	ob_tmed05_ref_req     	varchar(100),
	ob_tmed06_valdtn_req  	varchar(100),
	ob_tpay10_post_to_gross_rcpt  varchar(100),
	ob_tpay11_post_to_chg_rcpts   varchar(100),
	ob_tmed12_exempt_auto_svc     varchar(100),
	ob_tpay17_halo_active 	varchar(100),
	ob_tstl17_chain_order 	varchar(100),
	ob_tpay18_halo_by_amt 	varchar(100),
	ob_tstl18_dont_fire_order     varchar(100),
	ob_tpay19_emp_meal    	varchar(100),
	ob_tstl19_reprint_chk 	varchar(100),
	ob_tdec19_tips_paid   	varchar(100),
	ob_tmed20_prn_sls_itmzrs      varchar(100),
	ob_tmed21_prn_summ_ttls       varchar(100),
	ob_tmed22_prn_trlr    	varchar(100),
	ob_tmed23_prn_chk     	varchar(100),
	ob_tmed24_prn_vat_ttl 	varchar(100),
	ob_tpay25_req_expr_date_entr  varchar(100),
	ob_tpay26_allow_recall        varchar(100),
	ob_tmed27_allow_curr_cnv      varchar(100),
	ob_tpay28_pms_post_0  	varchar(100),
	ob_tpay29_prn_2_pms_ref       varchar(100),
	ob_tpay30_19_digit_pms_ref    varchar(100),
	ob_tpay31_enable_pms  	varchar(100),
	ob_tpay33_dont_net_pms_chng   varchar(100),
	ob_tpay34_cc_post_to_pms      varchar(100),
	ob_tmed35_prn_memo_chk        varchar(100),
	ob_tstl36_prn_seat_chk        varchar(100),
	ob_tmed37_incr_filter 	varchar(100),
	ob_tpay38_prn_fcr_chk 	varchar(100),
	ob_tpay39_post_fcr_credit     varchar(100),
	ob_tpay38_prn_personal_chk    varchar(100),
	ob_tpay41_req_ca      	varchar(100),
	ob_tpay42_prompt_ca_imm_pymt  varchar(100),
	ob_tpay43_dont_save_pms_resp  varchar(100),
	ob_tpay44_tax_exempt_coupon   varchar(100),
	ob_tpay45_vrfy_cc_mod_10      varchar(100),
	ob_tpay46_dont_chk_expr_date  varchar(100),
	ob_tpay47_prn_with_lookup     varchar(100),
	ob_tpay48_no_valdt_expr_date  varchar(100),
	ob_tpay49_tnd_must_excd_tip   varchar(100),
	ob_tmed50_sort_mi_by_seat     varchar(100),
	ob_tpay51_prompt_cc_issu_num  varchar(100),
	ob_tpay52_prompt_cc_iss_date  varchar(100),
	ob_tpay53_prompt_opt_trlr     varchar(100),
	ob_tpay54_cc_final_amt_reqd   varchar(100),
	ob_tstl38_prn_on_rcpt_prntr   varchar(100),
	ob_tstl43_prn_shared_chk      varchar(100),
	ob_tstl51_suspend_trans       varchar(100),
	ob_item_shareable     	varchar(100),
	ob_tpay_no_trlr_multi_round   varchar(100),
	ob_tpay_prn_thai_tax_ar_line  varchar(100),
	ob_tpay_prn_thai_tax_invoice  varchar(100),
	ob_tstl_send_order    	varchar(100),
	ob_allow_with_euro    	varchar(100),
	ob_mask_cc_number     	varchar(100),
	ob_debit_card 		varchar(100),
	ob_dd_svc_ttl_key     	varchar(100),
	ob_prompt_during_keyed_ca     varchar(100),
	ob_prompt_for_cashback        varchar(100),
	ob_override_sign_out  	varchar(100),
	ob_rsvd05     		varchar(100),
	ob_pin_reqd   		varchar(100),
	ob_mask_cc_exp      varchar(100),
	ob_rsvd08     		varchar(100),
	ob_rsvd09     		varchar(100),
	priv_lvl      		varchar(100),
	tax_class_seq 		varchar(100),
	pms   			varchar(100),
	class_seq        	varchar(100),
	prn_def_class_seq     	varchar(100),
	chg_tip_dsvc_seq      	varchar(100),
	tmed_slu_seq  		varchar(100),
	nlu_num       		varchar(100),
	key_num       		varchar(100),
	icon_id       		varchar(100),
	halo  			float NULL ,
	cat   			varchar(100),
	ca_tip_pct    		float,
	ca_diff_pct   		float,
	ca_scndary_flr_limit  	float NULL ,
	ca_init_auth_amt      	float NULL ,
	effective_from        	datetime NULL ,
	effective_to  		datetime NULL ,
	ca_driver     		varchar(100),
	edc_driver    		varchar(100),
	autofire_mode 		varchar(100),
	last_updated_by       	varchar(100),
	last_updated_date     	datetime NULL ,
	ob_selective_fire     	varchar(100),
	ob_keep_held_status   	varchar(100),
	ob_personal_check     	varchar(100),
	ob_prompt_for_ssn     	varchar(100),
	ob_print_endorsement_trailer  varchar(100),
	ob_mask_cardholder_name       varchar(100),
	ob_rnd_tender 		varchar(100),
	ob_rnd_zero_tens      	varchar(100),
	ob_rnd_tens_digit     	varchar(100),
	insignificant_digits  	varchar(100),
	external_type 		integer NULL ,
	ca_base_flr_lmt_1     	float NULL ,
	ca_base_flr_lmt_2     	float NULL ,
	ob_offline_base_flr_lmt_1     varchar(100),
	ob_offline_base_flr_lmt_2     varchar(100),
	ob_prnt_vchr_base_flr_lmt_1   varchar(100),
	ob_prnt_vchr_base_flr_lmt_2   varchar(100),
	ob_no_prompt_avs      	varchar(100),
	ob_manual_entry_req_cvv       varchar(100),
	ob_require_cvv        	varchar(100),
	ob_dflt_force_tbl_entry_svc_ttl varchar(100)
	,ImportDateTime datetime
)

CREATE TABLE tmed_dtl
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	trans_seq     		varchar(100) NOT NULL ,
	dtl_seq       		varchar(100) NOT NULL ,
	tmed_seq      		varchar(100) NOT NULL ,
	other_emp_seq 		varchar(100),
	ob_tax_1_exempt       	varchar(100),
	ob_tax_2_exempt       	varchar(100),
	ob_tax_3_exempt       	varchar(100),
	ob_tax_4_exempt       	varchar(100),
	ob_tax_5_exempt       	varchar(100),
	ob_tax_6_exempt       	varchar(100),
	ob_tax_7_exempt       	varchar(100),
	ob_tax_8_exempt       	varchar(100),
	cc_acct_num   		char(20) NULL ,
	expiration_date       	char(4) NULL ,
	chg_tip_ttl   		float NOT NULL ,
	allocated_tax_ttl     	float NOT NULL ,
	type_def      		binary(8) NOT NULL ,
	ob_immed_pymnt        	varchar(100),
	ob_tips_paid  		varchar(100),
	frgn_cncy_seq 		varchar(100),
	frgn_cncy_ttl 		varchar(100) NULL ,
	frgn_cncy_num_decimal_places  varchar(100),
	cashback_ttl  		float NULL ,
	cm_till_id    		varchar(100),
	ssn   			char(20) NULL ,
	pers_chk_transit_num  	char(10) NULL ,
	pers_chk_acct_num     	char(14) NULL ,
	pers_chk_chk_num      	char(7) NULL ,
	print_class_seq       	varchar(100),
	pms_if_seq    		varchar(100),
	tray_totaled_seat_map 	binary(4) NULL ,
	encrypt_value_seq     	varchar(100)
	,ImportDateTime datetime
)

CREATE TABLE trk_grp_def
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	trk_grp_seq   		varchar(100) NOT NULL ,
	obj_num       		varchar(100) NOT NULL ,
	name  			varchar(100) NULL ,
	ob_grp_in_use 		varchar(100),
	last_updated_date     	varchar(100) NULL ,
	last_updated_by       	varchar(100)
	,ImportDateTime datetime
)

CREATE TABLE trk_ttl_def
(
	SerialKey		varchar(100) NOT NULL PRIMARY KEY,
	trk_grp_seq   		varchar(100) NOT NULL ,
	trk_ttl_seq   		varchar(100) NOT NULL ,
	name  			varchar(100) NULL ,
	ttl_type      		varchar(100),
	ttl_num       		varchar(100),
	last_updated_by       	varchar(100)
	,ImportDateTime datetime
)

